---
title: "HW#4"
author: "Tyler Cobian"
date: "4/25/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include=FALSE}
library(tidyverse)
data<- read_csv("HW_#2.csv")

```

Make a plot for the demand curves

```{r}
demand_1<- ggplot(data, aes(x = Q_Low_Gallons_per_Day, y = Price_Dollars))+
  geom_smooth()
demand_1

demand_2<- ggplot(data, aes(x = Q_High_Gallons_per_Day, y = Price_Dollars))+
  geom_smooth()
demand_2
```

linear model of the the demand

```{r}
demand_low_lm<- lm(data$Price_Dollars ~ data$Q_Low_Gallons_per_Day)
plot(demand_low_lm)
summary(demand_low_lm)

demand_high_lm<- lm(data$Price_Dollars ~ data$Q_High_Gallons_per_Day)
plot(demand_high_lm)
summary(demand_high_lm)

# Equation for Low demand
alpha_low<- 2.199e+01
beta_low<- -1.355e-04
# p = alpha + beta(quantity)

#Equation for high
alpha_high<- 2.339e+01
beta_high<- -1.297e-04
# p = alpha + beta(quantity)

Q_low1<- (1/beta_low)
Q_low2<- (alpha_low/-beta_low)
# Q_low = Q_low1*P + Q_low2
# equation for low demand group

Q_high1<- (1/beta_high)
Q_high2<- (alpha_high/-beta_high)
# Q_high = Q_high1*P + Q_high2
# equation for high demand group

Q_agg1<- Q_low1+Q_high1 # aggreagte low demand
Q_agg2<- Q_low2+Q_high2 # aggregate high demand

P_agg1<- 1/Q_agg1 # price for low demand
P_agg2<- -Q_agg2/Q_agg1 # price for high demand

# Supply curve

supply<- 5/((5-P_agg2)/P_agg1)
```
Functions - making the lines from values above

```{r}
#low demand curve
demand_low<- function(x){alpha_low+beta_low*x}

# high demand curve
demand_high<- function(x){alpha_high+beta_high*x}

# aggregate demand curve
demand_agg<- function(x){P_agg2+P_agg1*x}

# Supply curve
supply_curve<- function(x){supply*x}

# marginal external cost curve
mec<- function(x){2 + 0*x}
```
Graphing out the functions

```{r}
# optimum point on th graph

opt<- data.frame(x = c(0:267176.2), y = c(5))
x<- 70000:500000

graph_1<- ggplot(data.frame(x = c(70000:500000)), aes(x=x))+
  stat_function(fun = demand_low, color = "darkblue")+
  stat_function(fun = demand_high, color = "darkorange")+
  stat_function(fun = demand_agg, color = "darkgreen")+
  stat_function(fun = supply_curve, color = "pink")+
  stat_function(fun = mec, color = "darkred")+
  xlab("\nQuantity")+
  ylab("Price\n")+
  ggtitle("Intial Gas Market \n")+
  scale_y_continuous(limits = c(0,25), expand = c(0,0))+
  scale_x_continuous(limits = c(0,500000), expand = c(0,0))

graph_1


```
caalculating low demand consumer surplus

```{r}
low_base<- 125387.5 # how to get these #s??
low_height<- 162282.8
low_cs<- (1/2)*low_base*low_height
# consumer surplus for the low demand  = 10174117292




```




























